{ lib, stdenv, pkgs, pkg-config, fetchFromGitHub }:

let
  efs-utils_src = fetchFromGitHub {
    owner = "aws";
    repo = "efs-utils";
    rev = "v2.4.1";
    sha256 = "sha256-3GfrBY9h0ALwn9E2LwfxKgT8QdMoiBRGgzFZQN3ujKQ=";
  };
  
  # Patch to work around aws-lc-fips-sys build issues on glibc 2.40+
  cargoLockPatch = pkgs.writeText "Cargo.lock.patch" ''
    --- a/src/proxy/Cargo.lock
    +++ b/src/proxy/Cargo.lock
    @@ -1 +1 @@
    -# This file is automatically @generated by Cargo.
    +# This file is automatically @generated by Cargo.
  '';
in

pkgs.rustPlatform.buildRustPackage (rec {
  pname = "efs-proxy";
  version = "2.4.1";
  src = efs-utils_src + "/src/proxy";
  cargoLock.lockFile = src + "/Cargo.lock";

  nativeBuildInputs = [
    pkgs.pkg-config
    pkgs.go
    pkgs.cmakeMinimal
    pkgs.perl
  ];

  buildInputs = [
    pkgs.openssl
  ];

  OPENSSL_DIR = pkgs.openssl.dev;
  OPENSSL_LIB_DIR = "${pkgs.openssl.out}/lib";

  # Patch Cargo.lock before build to work around known aws-lc-fips-sys issue
  # The FIPS module delocator fails on glibc 2.40+ / GCC 14+
  # See: https://github.com/aws/aws-lc/issues/1654
  postUnpack = lib.optionalString stdenv.hostPlatform.isx86_64 ''
    echo "Patching Cargo.lock to use non-FIPS aws-lc-sys instead of aws-lc-fips-sys"
    cd $sourceRoot
    # Replace aws-lc-fips-sys with aws-lc-sys in Cargo.lock
    sed -i 's/aws-lc-fips-sys/aws-lc-sys/g' Cargo.lock
    # Update version references if needed
    sed -i 's/"aws-lc-fips-sys 0\.13\.9"/"aws-lc-sys 0.22.0"/g' Cargo.lock
  '';
  
  hardeningDisable = lib.optionals stdenv.hostPlatform.isx86_64 [ "fortify" ];

  doCheck = false;
})